/** Fotmob / RapidAPI country codes → ISO-style file codes used in ClubGlobe. */
export const AFRICA_CCODE_MAP: Record<
  string,
  { country: string; countryCode: string }
> = {
  ALG: { country: 'Algeria', countryCode: 'DZ' },
  EGY: { country: 'Egypt', countryCode: 'EG' },
  GHA: { country: 'Ghana', countryCode: 'GH' },
  MAR: { country: 'Morocco', countryCode: 'MA' },
  NGA: { country: 'Nigeria', countryCode: 'NG' },
  RSA: { country: 'South Africa', countryCode: 'ZA' },
  TUN: { country: 'Tunisia', countryCode: 'TN' },
  KEN: { country: 'Kenya', countryCode: 'KE' },
  SEN: { country: 'Senegal', countryCode: 'SN' },
  CIV: { country: 'Ivory Coast', countryCode: 'CI' },
  CMR: { country: 'Cameroon', countryCode: 'CM' },
  UGA: { country: 'Uganda', countryCode: 'UG' },
  ZAM: { country: 'Zambia', countryCode: 'ZM' },
  ZIM: { country: 'Zimbabwe', countryCode: 'ZW' },
  BOT: { country: 'Botswana', countryCode: 'BW' },
  NAM: { country: 'Namibia', countryCode: 'NA' },
  MOZ: { country: 'Mozambique', countryCode: 'MZ' },
  ANG: { country: 'Angola', countryCode: 'AO' },
  ETH: { country: 'Ethiopia', countryCode: 'ET' },
  MLI: { country: 'Mali', countryCode: 'ML' },
  BFA: { country: 'Burkina Faso', countryCode: 'BF' },
  GAB: { country: 'Gabon', countryCode: 'GA' },
  CGO: { country: 'Congo', countryCode: 'CG' },
  COD: { country: 'DR Congo', countryCode: 'CD' },
  RWA: { country: 'Rwanda', countryCode: 'RW' },
  BDI: { country: 'Burundi', countryCode: 'BI' },
  LBY: { country: 'Libya', countryCode: 'LY' },
  SDN: { country: 'Sudan', countryCode: 'SD' },
  GIN: { country: 'Guinea', countryCode: 'GN' },
  BEN: { country: 'Benin', countryCode: 'BJ' },
  TOG: { country: 'Togo', countryCode: 'TG' },
  NIG: { country: 'Niger', countryCode: 'NE' },
  MWI: { country: 'Malawi', countryCode: 'MW' },
  LES: { country: 'Lesotho', countryCode: 'LS' },
  SWZ: { country: 'Eswatini', countryCode: 'SZ' },
  MAD: { country: 'Madagascar', countryCode: 'MG' },
  MRI: { country: 'Mauritius', countryCode: 'MU' },
  SEY: { country: 'Seychelles', countryCode: 'SC' },
  GAM: { country: 'Gambia', countryCode: 'GM' },
  GNB: { country: 'Guinea-Bissau', countryCode: 'GW' },
  CPV: { country: 'Cape Verde', countryCode: 'CV' },
  STP: { country: 'São Tomé and Príncipe', countryCode: 'ST' },
  EQG: { country: 'Equatorial Guinea', countryCode: 'GQ' },
  CHA: { country: 'Chad', countryCode: 'TD' },
  MTN: { country: 'Mauritania', countryCode: 'MR' },
  TAN: { country: 'Tanzania', countryCode: 'TZ' },
  LIB: { country: 'Liberia', countryCode: 'LR' },
  SLE: { country: 'Sierra Leone', countryCode: 'SL' },
  ERI: { country: 'Eritrea', countryCode: 'ER' },
  DJI: { country: 'Djibouti', countryCode: 'DJ' },
  SOM: { country: 'Somalia', countryCode: 'SO' },
  COM: { country: 'Comoros', countryCode: 'KM' },
  SSD: { country: 'South Sudan', countryCode: 'SS' },
  CAF: { country: 'Central African Republic', countryCode: 'CF' },
}
