/** Fotmob / RapidAPI country codes → ISO file codes used in ClubGlobe. */
export const ASIA_CCODE_MAP: Record<
  string,
  { country: string; countryCode: string }
> = {
  JPN: { country: 'Japan', countryCode: 'JP' },
  KOR: { country: 'South Korea', countryCode: 'KR' },
  CHN: { country: 'China', countryCode: 'CN' },
  TPE: { country: 'Taiwan', countryCode: 'TW' },
  HKG: { country: 'Hong Kong', countryCode: 'HK' },
  IND: { country: 'India', countryCode: 'IN' },
  PAK: { country: 'Pakistan', countryCode: 'PK' },
  BAN: { country: 'Bangladesh', countryCode: 'BD' },
  SRI: { country: 'Sri Lanka', countryCode: 'LK' },
  NEP: { country: 'Nepal', countryCode: 'NP' },
  AFG: { country: 'Afghanistan', countryCode: 'AF' },
  THA: { country: 'Thailand', countryCode: 'TH' },
  VNM: { country: 'Vietnam', countryCode: 'VN' },
  IDN: { country: 'Indonesia', countryCode: 'ID' },
  MAS: { country: 'Malaysia', countryCode: 'MY' },
  SIN: { country: 'Singapore', countryCode: 'SG' },
  PHI: { country: 'Philippines', countryCode: 'PH' },
  MYA: { country: 'Myanmar', countryCode: 'MM' },
  CAM: { country: 'Cambodia', countryCode: 'KH' },
  LAO: { country: 'Laos', countryCode: 'LA' },
  BRU: { country: 'Brunei', countryCode: 'BN' },
  TLS: { country: 'Timor-Leste', countryCode: 'TL' },
  KSA: { country: 'Saudi Arabia', countryCode: 'SA' },
  UAE: { country: 'United Arab Emirates', countryCode: 'AE' },
  QAT: { country: 'Qatar', countryCode: 'QA' },
  KUW: { country: 'Kuwait', countryCode: 'KW' },
  BHR: { country: 'Bahrain', countryCode: 'BH' },
  OMA: { country: 'Oman', countryCode: 'OM' },
  IRQ: { country: 'Iraq', countryCode: 'IQ' },
  IRN: { country: 'Iran', countryCode: 'IR' },
  ISR: { country: 'Israel', countryCode: 'IL' },
  JOR: { country: 'Jordan', countryCode: 'JO' },
  LIB: { country: 'Lebanon', countryCode: 'LB' },
  SYR: { country: 'Syria', countryCode: 'SY' },
  YEM: { country: 'Yemen', countryCode: 'YE' },
  KAZ: { country: 'Kazakhstan', countryCode: 'KZ' },
  UZB: { country: 'Uzbekistan', countryCode: 'UZ' },
  TKM: { country: 'Turkmenistan', countryCode: 'TM' },
  KGZ: { country: 'Kyrgyzstan', countryCode: 'KG' },
  TJK: { country: 'Tajikistan', countryCode: 'TJ' },
  GEO: { country: 'Georgia', countryCode: 'GE' },
  ARM: { country: 'Armenia', countryCode: 'AM' },
  AZE: { country: 'Azerbaijan', countryCode: 'AZ' },
  MNG: { country: 'Mongolia', countryCode: 'MN' },
}
